### ISSUE TITLE
Configure Gitlab to Build and Deliver an Example Algorithm

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-ads-deployment#47]
Configure Gitlab to build and deliver to the algorithm catalog an example U-ADS algorithm.

**Comment by mcduffie** [comment]
Full unity-app-generator process

```
build_ogc_app.py init $git_url $tmp_dir

cd $tmp_dir
build_ogc_app.py build_docker
build_ogc_app.py push_docker $APPGEN_DOCKER_URL
build_ogc_app.py build_cwl
build_ogc_app.py push_app_registry --api_url $APPGEN_DOCKSTORE_URL --token $APPGEN_DOCKSTORE_TOKEN
```

**Comment by edwinsarkissian** [comment]
James,

If  $CI_PROJECT_DIR  is the path to a locally cloned git repository, would the following three steps be correct?  (Note that push processes are not included yet, and I am not doing any “cd” like your example code below.)

python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py init $CI_PROJECT_DIR
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py build_docker
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py build_cwl

I believe build_docker is executed correctly because I see its image in local docker registery:

sh-4.2$ sudo docker images
REPOSITORY                  TAG        IMAGE ID       CREATED         SIZE
unity-example-application   4331df7a   d06c4fe8e066   8 minutes ago   1.63GB
buildpack-deps              bionic     0f137f206fa8   2 months ago    621MB
ubuntu

What would indicate that  build_cwl has worked as well?

Thanks,
Edwin

From: James McDuffie ***@***.***>
Reply-To: unity-sds/unity-ads-deployment ***@***.***>
Date: Tuesday, July 25, 2023 at 10:44 AM
To: unity-sds/unity-ads-deployment ***@***.***>
Cc: "Sarkissian, Edwin (US 398E)" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [unity-sds/unity-ads-deployment] Configure Gitlab to Build and Deliver an Example Algorithm (Issue #47)


Full unity-app-generator process

build_ogc_app.py init $git_url $tmp_dir



cd $tmp_dir

build_ogc_app.py build_docker

build_ogc_app.py push_docker $APPGEN_DOCKER_URL

build_ogc_app.py build_cwl

build_ogc_app.py push_app_registry --api_url $APPGEN_DOCKSTORE_URL --token $APPGEN_DOCKSTORE_TOKEN

**Comment by mcduffie** [comment]
In the $CI_PROJECT_DIR directory there should be a .unity_app_gen/cwl directory if build_cwl stage succeeded.

**Comment by edwinsarkissian** [comment]
James,

If I understand the comments at https://github.com/unity-sds/unity-app-generator/blob/main/README.md correctly, I should be able to do the following

cd $CI_PROJECT_DIR
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py init
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py build_docker
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py build_cwl

I am following the example

git clone https://github.com/unity-sds/unity-example-application.git
cd unity-example-application
build_ogc_app.py init

given in the same REAME file, but I get the following error message:

$ cd $CI_PROJECT_DIR
$ python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py init
usage: build_ogc_app.py init [-h] [-c CHECKOUT] source_repository [destination_directory]
build_ogc_app.py init: error: the following arguments are required: source_repository

Is there anything that I am doing wrong?

Edwin


From: James McDuffie ***@***.***>
Reply-To: unity-sds/unity-ads-deployment ***@***.***>
Date: Tuesday, August 1, 2023 at 3:15 PM
To: unity-sds/unity-ads-deployment ***@***.***>
Cc: "Sarkissian, Edwin (US 398E)" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [unity-sds/unity-ads-deployment] Configure Gitlab to Build and Deliver an Example Algorithm (Issue #47)


In the $CI_PROJECT_DIR directory there should be a .unity_app_gen/cwl directory if build_cwl stage succeeded.

**Comment by mcduffie** [comment]
If you cd to the project directory then there needs to be a dot “.” after init to specify the current directory.

On Aug 1, 2023, at 3:40 PM, edwinsarkissian ***@***.***> wrote:

﻿

James,

If I understand the comments at https://github.com/unity-sds/unity-app-generator/blob/main/README.md correctly, I should be able to do the following

cd $CI_PROJECT_DIR
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py init
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py build_docker
python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py build_cwl

I am following the example

git clone https://github.com/unity-sds/unity-example-application.git
cd unity-example-application
build_ogc_app.py init

given in the same REAME file, but I get the following error message:

$ cd $CI_PROJECT_DIR
$ python3 /home/gitlab-runner/unity-app-generator/build_ogc_app.py init
usage: build_ogc_app.py init [-h] [-c CHECKOUT] source_repository [destination_directory]
build_ogc_app.py init: error: the following arguments are required: source_repository

Is there anything that I am doing wrong?

Edwin


From: James McDuffie ***@***.***>
Reply-To: unity-sds/unity-ads-deployment ***@***.***>
Date: Tuesday, August 1, 2023 at 3:15 PM
To: unity-sds/unity-ads-deployment ***@***.***>
Cc: "Sarkissian, Edwin (US 398E)" ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [unity-sds/unity-ads-deployment] Configure Gitlab to Build and Deliver an Example Algorithm (Issue #47)


In the $CI_PROJECT_DIR directory there should be a .unity_app_gen/cwl directory if build_cwl stage succeeded.

**Comment by edwinsarkissian** [comment]
This task is complete.  The Unity cloning tool (https://github.com/unity-sds/unity-app-build-trigger) and unity-app-generator (https://github.com/unity-sds/unity-app-generator) have been successfully tested with the example project https://github.com/unity-sds/unity-example-application.
